name: sample
description: "Sample pubspec.yaml file for Device-Agnostic Design"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.6
  flutter_form_builder: 9.4.1
  form_builder_validators: 11.0.0
  hive_ce: ^2.1.0 # Add this
  hive_ce_flutter: ^2.1.0 # Add this

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
